server:
  port: 8001

spring:
  application:
    name: hystrix-payment-provider



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

